### ISSUE TITLE
unable to compile example code

### ISSUE THREAD

**Issue by mmanoj** [noporpoise/jelly-hash#1]
I'm getting below error while comple example:

c -Wall -Wextra -O3 -o jellyTest jellyTest.c num_format.c -lpthread -lm
jellyTest.c: In function ‘main’:
jellyTest.c:24:24: error: incompatible type for argument 1 of ‘jelly_hash_find’
 hpos = jelly_hash_find(jhash, in, 1, &inserted);
                        ^
In file included from jellyTest.c:11:0:
jellyhash.h:421:20: note: expected ‘JellyHash * {aka struct <anonymous> *}’ but argument is of type ‘JellyHash {aka struct <anonymous>}’
 static inline HKey jelly_hash_find(JellyHash *jh, const char *key,
                    ^
jellyTest.c:28:24: error: incompatible type for argument 1 of ‘jelly_hash_find’
 hpos = jelly_hash_find(jhash, in, 0, &inserted);
                        ^
In file included from jellyTest.c:11:0:
jellyhash.h:421:20: note: expected ‘JellyHash * {aka struct <anonymous> *}’ but argument is of type ‘JellyHash {aka struct <anonymous>}’
 static inline HKey jelly_hash_find(JellyHash *jh, const char *key,
                    ^
jellyTest.c:30:20: error: incompatible type for argument 1 of ‘jelly_hash_get_key’
 jelly_hash_get_key(jhash, hpos, out); // get value for `key`
                    ^
In file included from jellyTest.c:11:0:
jellyhash.h:548:20: note: expected ‘const JellyHash * {aka const struct <anonymous> *}’ but argument is of type ‘JellyHash {aka struct <anonymous>}’
 static inline void jelly_hash_get_key(const JellyHash *jh, HKey loc, char *key)
                    ^
Makefile:14: recipe for target 'jellyTest' failed
make: *** [jellyTest] Error 1

**Comment by mmanoj** [comment]
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <unistd.h>
#include <pthread.h>
#include <assert.h>
#include <time.h> // srand

#include "num_format.h"

#include "jellyhash.h"

int main () {

JellyHash jhash;
jelly_hash_alloc(&jhash, 7, 20, 16); // 20*2^7 entries, 16 bits each

char in[10] , out[10];
HKey hpos;
int inserted;

// Find or insert beef
strcpy(in, "Beef");
hpos = jelly_hash_find(jhash, in, 1, &inserted);
if(hpos == JHASH_NULL) exit(-1); // hash table full

// Where's the beef? Find and get value from key
hpos = jelly_hash_find(jhash, in, 0, &inserted);
if(hpos == JHASH_NULL) exit(-1); // entry not found
jelly_hash_get_key(jhash, hpos, out); // get value for `key`
//printf("Found value at position %i: %s\n", (int)key, out);

jelly_hash_dealloc(&jhash);

return 0;

}

**Comment by noporpoise** [comment]
You need to pass a hash table pointer to `jelly_hash_find()`:

    hpos = jelly_hash_find(jhash, in, 1, &inserted);

should be:

    hpos = jelly_hash_find(&jhash, in, 1, &inserted);
